languageCode: vi-vn
copyright: This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License.
title: 12bit.vn links
description: Browse multiple web development sites at the same time.
baseURL: https://news.12bit.vn/
theme: news.12bit.vn
enableGitInfo: true
enableEmoji: true
enableRobotsTXT: true
googleAnalytics: UA-131517577-3
paginate: 40
outputs:
  home:
  - HTML
  - RSS
params:
  description: Browse multiple web development sites at the same time.
  favicon: img/favicon.png
  images:
    - img/home.png
  cta:
    title: Add my site
    url: 'https://github.com/12bitvn/news.12bit.vn'
blackfriday:
  hrefTargetBlank: true
  noreferrerLinks: true
menu:
  main:
  - identifier: contribute
    title: Thêm links
    url: /pages/about.html
taxonomies:
  language: language
