languageCode: vi-vn
copyright: This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License.
title: 12bit.vn
description: write and share to learn
baseURL: https://news.12bit.vn/
theme: news.12bit.vn
enableGitInfo: true
enableEmoji: true
enableRobotsTXT: true
googleAnalytics: UA-131517577-1
paginate: 40
outputs:
  home:
  - HTML
  - RSS
params:
  description: write and share to learn
  favicon: img/icon/favicon.png
  images:
    - img/index.png
blackfriday:
  hrefTargetBlank: true
  noreferrerLinks: true
menu:
  main:
  - identifier: about
    title: Giới thiệu
    url: /pages/about.html
  - identifier: chat
    title: Chat
    url: https://discord.gg/uMJxpXB
  - identifier: til
    title: TIL
    url: https://til.12bit.vn
  footer:
    - identifier: 0
      title: Series
      url: /series.html
    - identifier: 1
      title: Shortcodes
      url: /pages/shortcodes.html
    - identifier: 2
      title: Donate
      url:  https://ko-fi.com/12bitvn
    - identifier: 3
      title: RSS
      url: /index.xml
