[build]
    publish = "public"
    functions = "bin"
    command = "make build"

[build.environment]
  GO_IMPORT_PATH = "github.com/12bitvn/news.12bit.vn"
  HUGO_VERSION = "0.48"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
    command = "make build --buildFuture -b $DEPLOY_PRIME_URL"
