[build]
publish = "public"
functions = "functions"
command = "build"

[build.environment]
  GO_IMPORT_PATH = "github.com/12bitvn/news.12bit.vn"
  HUGO_VERSION = "0.48"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "hugo --buildFuture -b $DEPLOY_PRIME_URL"
